name: "Publish to Winget Manually"
on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag you want publish
        required: true

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: yourmoln.moligeek
          installers-regex: '.exe$' # Only .exe files
          version: ${{ inputs.tag }}
          token: ${{ secrets.WINGET_TOKEN }}
